#!/bin/bash
#2016-04-28 add some notes
#delete the files for lab_1, before start a new lab, this script should be excuted
rm -rf /tmp/iou/lab_1/*
flag=`ls /tmp/iou/lab_1 | grep dev`
if [ "$flag" = "" ]; then
	back="succeed"
else
	back="failed"
fi
printf 'Content-Type: text/html\r\n\r\n'
echo $back
