#!/bin/bash
#for centos6.5 and ubuntu14
eth=`ifconfig -a | awk '/eth/{print $1,$4}'`
printf 'Content-Type: text/html\r\n\r\n'
	cat <<EOF
<html>
	<head>
		<title>eth_mac</title>
	</head>
	<body>
		<pre>$eth</pre>
	</body>
</html>
EOF
