#!/bin/bash
#input: user@ip (ssh $user@192.168.1.$ip)
#request method: get
#20160429 add some notes

function connect {
	/opt/iou/bin/shellinaboxd --cgi=20000-25000  -s "/:$(id -u):$(id -g):HOME:ssh $1@192.168.1.$2 "
	if [ $? -ne 0 ]; then
		cannot_connect
	fi
}

function default {
	# First time that the CGI script was called. Show initial HTML page.
	printf 'Content-Type: text/html\r\n\r\n'
	cat << EOF
<html>
	<head>
		<title>ssh Shell</title>
	</head>
	<body>
		<h1>ssh Shell</h1>
	</body>
</html>	
EOF
}

function cannot_connect {
	printf 'Content-Type: text/html\r\n\r\n'
	cat <<EOF
<html>
	<head>
		<title>ssh Shell</title>
	</head>
	<body>
		<h1>ssh Shell</h1>
		<p>Unable to establish connection with $parms</p>
	</body>
</html>
EOF
}

case "${REQUEST_METHOD}" in
	GET)
		# Retrieve CGI parameter, then start shellinabox with this address
		parms=`echo $QUERY_STRING`
		user=`echo $parms | cut -d @ -f 1`
		ip=`echo $parms | cut -d @ -f 2`
		if [ "$parms" != "" ]; then
			connect $user $ip
		else
			default
		fi
	;;
	*)
		default
	;;
esac  
