#!/bin/bash
#20160429 add some notes
#telnet.conf: recording users, ports, pids, and time
#portx.conf: the conf file for rinetd

now=`date '+%Y-%m-%d>%H:%M:%S'`
#get parms, parms must be like this: user@ip@devs, devs should be the id of devices, separated by ','
parms=`echo $1`
if [ "parms" == "" ];then
	parms=`echo $QUERY_STRING`
fi
if [ "$parms" == ""  ];then
	printf 'Content-Type: text/html\r\n\r\n'
	echo "no parms"
	exit 0
else
	user=`echo $parms|cut -d '@' -f1`
	ip=`echo $parms|cut -d '@' -f2`
	devs=`echo $parms|cut -d '@' -f3|sed 's/\,/\ /g'`#get devs, and replace the ',' with ' '
fi

#start auto checkPort
autocheck=`ps -ef|grep checkPort|grep -v 'grep'`
if [ "$autocheck" == "" ];then
	/opt/iou/cgi-bin/checkPort 1>/dev/null &
	echo "start auto check $now">>telnet.log
fi

#check for user
userexist=`awk '/'$user'/{print $2}' telnet.conf`
if [ "$userexist" != "" ];then
	./telnet_kill $userexist 1>/dev/null	
fi

#generate userid, no more than 50 users
userid=`tail -1 telnet.conf| awk '{print $1}'`
userid=`expr $userid + 1`
if [ $userid -gt 50 ];then
	$userid=`expr $userid - 50`
fi

#generate port.conf, and output the http stream
#port range: 25000-30000
baseport=`expr $userid \* 50 + 25000`
touch port$userid.conf
: > port$userid.conf
printf 'Content-Type: text/html\r\n\r\n'
cat <<EOF
<html>
<head>
<title>Telnet Shell</title>
</head>
<body>
EOF
for dev in $devs
do
	lport=`expr $baseport + $dev` #local port
	rport=`expr $dev + 2000` #remote port in iou
	echo "0.0.0.0 $lport 192.168.1.$ip $rport">>port$userid.conf
	echo "<h1>$dev-$lport</h1>" #output to the html
done

cat <<EOF
</body>
</html>
EOF

#rinetd
/opt/iou/cgi-bin/rinetd -c port$userid.conf 1>/dev/null
pid=`ps -ef|grep port$userid.conf|grep -v grep|awk '{print $2}'`
if [ "$pid" == "" ];then
	pid=0
fi
echo "$userid $user $ip $pid $now">>telnet.conf
echo "$user in pid=$pid $now">>telnet.log

